%% driverModel_clean.m
% Builds FASTCORMICS models for:
%
% CELL LINES
%   Huh7  -> DMEM
%   769-p -> RPMI
%
% TCGA
%   KICH -> RPMI
%   KIRC -> RPMI
%   KIRP -> RPMI
%   LIHC -> DMEM
%   preserves the original FASTCORMICS settings;
%   loads consistent_model.mat and dico2columns.mat;
%   creates the medium .mat variables from the Excel files;
%   uses RPMI for KICH, KIRC, KIRP and 769-p;
%   uses DMEM for LIHC and Huh7;
%   builds TCGA ON/OFF consensus models;
%   builds Huh7 and 769-p consensus models;
%   optionally builds sample-specific models;
%   searches first in cfg.preparedDir, then in cfg.rootDir for discretized files.
% 
%   The FASTCORMICS settings below match your original code: oxygen closure, already_mapped_tag = 0, consensus_proportion = 0.9, epsilon = 1e-4, the same unpenalized systems, and the same forced reactions.
%   MATLAB R2019b compatible.

clear;
close all;
clc;

feature astheightlimit 2000
solverOK = 1;

cfg = pipeline_config;

%% ============================================================
% USER OPTIONS
%% ============================================================

% Build consensus models using all samples in each group.
buildConsensusModels = true;

% Build one model for every individual sample.
% This can take a very long time.
buildCellLineSampleModels = true;
buildTCGASampleModels = true;

%% Make sure output folder exists

if exist(cfg.modelsDir, 'dir') ~= 7
    mkdir(cfg.modelsDir);
end

%% ============================================================
% LOAD MODEL AND DICTIONARY
%% ============================================================

if exist(cfg.modelFile, 'file') ~= 2
    error('Missing model file: %s', cfg.modelFile);
end

if exist(cfg.dicoFile, 'file') ~= 2
    error('Missing dictionary file: %s', cfg.dicoFile);
end

load(cfg.modelFile, 'consistent_model');
load(cfg.dicoFile, 'dico');

fprintf('Loaded model:\n%s\n', cfg.modelFile);
fprintf('Loaded dictionary:\n%s\n', cfg.dicoFile);

%% Original oxygen setting — unchanged

oxygenMask = ismember( ...
    consistent_model.rxns, ...
    'EX_o2s[e]');

consistent_model.lb(oxygenMask) = 0;

%% ============================================================
% ORIGINAL FASTCORMICS SETTINGS — UNCHANGED
%% ============================================================

already_mapped_tag = 0;
consensus_proportion = 0.9;
epsilon = 1e-4;
biomass_rxn = 'biomass_reaction';

unpenalizedSystems = { ...
    'Transport, endoplasmic reticular';
    'Transport, extracellular';
    'Transport, golgi apparatus';
    'Transport, mitochondrial';
    'Transport, peroxisomal';
    'Transport, lysosomal';
    'Transport, nuclear'};

unpenalized = consistent_model.rxns( ...
    ismember( ...
        consistent_model.subSystems, ...
        unpenalizedSystems));

optional_settings = struct();

optional_settings.unpenalized = unpenalized;
optional_settings.not_medium_constrained = [];

optional_settings.func = { ...
    'DM_atp_c_', ...
    'biomass_reaction'};

%% ============================================================
% LOAD MEDIA FROM EXCEL AND CREATE MAT VARIABLES
%% ============================================================

if exist(cfg.mediumFiles.DMEM, 'file') ~= 2
    error('Missing DMEM Excel file: %s', cfg.mediumFiles.DMEM);
end

if exist(cfg.mediumFiles.RPMI, 'file') ~= 2
    error('Missing RPMI Excel file: %s', cfg.mediumFiles.RPMI);
end

fprintf('\nReading DMEM medium from Excel...\n');

medium_DMEM_H = readtable( ...
    cfg.mediumFiles.DMEM, ...
    'ReadVariableNames', false);

medium_DMEM_H = table2array(medium_DMEM_H);

save( ...
    fullfile(cfg.modelsDir, 'medium_DMEM_H.mat'), ...
    'medium_DMEM_H');

fprintf('Reading RPMI medium from Excel...\n');

medium_RPMI_7 = readtable( ...
    cfg.mediumFiles.RPMI, ...
    'ReadVariableNames', false);

medium_RPMI_7 = table2array(medium_RPMI_7);

save( ...
    fullfile(cfg.modelsDir, 'medium_RPMI_7.mat'), ...
    'medium_RPMI_7');

fprintf('Medium files created in:\n%s\n', cfg.modelsDir);

%% ============================================================
% CELL-LINE MODELS
%% ============================================================

if strcmpi(cfg.runMode, 'CELL_LINES') || ...
        strcmpi(cfg.runMode, 'ALL')

    fprintf('\n========================================\n');
    fprintf('CELL-LINE MODELS\n');
    fprintf('========================================\n');

    %% --------------------------------------------------------
    % Huh7 data
    %% --------------------------------------------------------

    huh7PreparedFile = find_prepared_file( ...
        cfg, ...
        'discretizedH.mat');

    fprintf('\nLoading Huh7 data:\n%s\n', huh7PreparedFile);

    H = load(huh7PreparedFile);

    requiredH = {'discretized', 'geneSyms', 'colnamesH'};

    check_required_variables(H, requiredH, huh7PreparedFile);

    discretizedH = H.discretized;
    geneSymsH = H.geneSyms;
    colnamesH = H.colnamesH;

    optional_settings.medium = medium_DMEM_H;

    %% Huh7 consensus models

    if buildConsensusModels

        fprintf('\nBuilding Huh7 consensus models...\n');

        [model_H_ctrl, ~] = fastcormics_RNAseq( ...
            consistent_model, ...
            discretizedH(:, [1, 2, 3, 11]), ...
            geneSymsH, ...
            dico, ...
            biomass_rxn, ...
            already_mapped_tag, ...
            consensus_proportion, ...
            epsilon, ...
            optional_settings);

        [model_H_sc1, ~] = fastcormics_RNAseq( ...
            consistent_model, ...
            discretizedH(:, 4:6), ...
            geneSymsH, ...
            dico, ...
            biomass_rxn, ...
            already_mapped_tag, ...
            consensus_proportion, ...
            epsilon, ...
            optional_settings);

        [model_H_sc2, ~] = fastcormics_RNAseq( ...
            consistent_model, ...
            discretizedH(:, 7:10), ...
            geneSymsH, ...
            dico, ...
            biomass_rxn, ...
            already_mapped_tag, ...
            consensus_proportion, ...
            epsilon, ...
            optional_settings);

        [model_H_sc12, ~] = fastcormics_RNAseq( ...
            consistent_model, ...
            discretizedH(:, 4:10), ...
            geneSymsH, ...
            dico, ...
            biomass_rxn, ...
            already_mapped_tag, ...
            consensus_proportion, ...
            epsilon, ...
            optional_settings);

        models_H_DMEMbiomass = { ...
            model_H_ctrl, ...
            model_H_sc1, ...
            model_H_sc12, ...
            model_H_sc2};

        save( ...
            fullfile(cfg.modelsDir, ...
            'models_H_DMEMbiomass.mat'), ...
            'models_H_DMEMbiomass');

    end

    %% Huh7 sample-specific models

    if buildCellLineSampleModels

        fprintf('\nBuilding Huh7 sample-specific models...\n');

        models_keep_Hsample = zeros( ...
            numel(consistent_model.rxns), ...
            numel(colnamesH));

        for i = 1:numel(colnamesH)

            fprintf('Huh7 sample %d of %d\n', ...
                i, numel(colnamesH));

            [ContextModel, A_keep] = fastcormics_RNAseq( ...
                consistent_model, ...
                discretizedH(:, i), ...
                geneSymsH, ...
                dico, ...
                biomass_rxn, ...
                already_mapped_tag, ...
                consensus_proportion, ...
                epsilon, ...
                optional_settings);

            sampleName = matlab.lang.makeValidName( ...
                colnamesH{i});

            outputFile = fullfile( ...
                cfg.modelsDir, ...
                ['Sample_Huh7_' sampleName '.mat']);

            save(outputFile, 'ContextModel');

            models_keep_Hsample(A_keep, i) = 1;

        end

        save( ...
            fullfile(cfg.modelsDir, ...
            'models_keep_Hsample.mat'), ...
            'models_keep_Hsample', ...
            'colnamesH');

    end

    %% --------------------------------------------------------
    % 769-p data
    %% --------------------------------------------------------

    p769PreparedFile = find_prepared_file( ...
        cfg, ...
        'discretized7.mat');

    fprintf('\nLoading 769-p data:\n%s\n', p769PreparedFile);

    P = load(p769PreparedFile);

    requiredP = {'discretized', 'geneSyms', 'colnames7'};

    check_required_variables(P, requiredP, p769PreparedFile);

    discretized7 = P.discretized;
    geneSyms7 = P.geneSyms;
    colnames7 = P.colnames7;

    optional_settings.medium = medium_RPMI_7;

    %% 769-p consensus models

    if buildConsensusModels

        fprintf('\nBuilding 769-p consensus models...\n');

        [model_7_ctrl, ~] = fastcormics_RNAseq( ...
            consistent_model, ...
            discretized7(:, [1, 2, 3, 4]), ...
            geneSyms7, ...
            dico, ...
            biomass_rxn, ...
            already_mapped_tag, ...
            consensus_proportion, ...
            epsilon, ...
            optional_settings);

        [model_7_sc1, ~] = fastcormics_RNAseq( ...
            consistent_model, ...
            discretized7(:, [5, 6, 7]), ...
            geneSyms7, ...
            dico, ...
            biomass_rxn, ...
            already_mapped_tag, ...
            consensus_proportion, ...
            epsilon, ...
            optional_settings);

        [model_7_sc2, ~] = fastcormics_RNAseq( ...
            consistent_model, ...
            discretized7(:, [8, 9, 10, 11]), ...
            geneSyms7, ...
            dico, ...
            biomass_rxn, ...
            already_mapped_tag, ...
            consensus_proportion, ...
            epsilon, ...
            optional_settings);

        [model_7_sc12, ~] = fastcormics_RNAseq( ...
            consistent_model, ...
            discretized7(:, 5:11), ...
            geneSyms7, ...
            dico, ...
            biomass_rxn, ...
            already_mapped_tag, ...
            consensus_proportion, ...
            epsilon, ...
            optional_settings);

        models_7_RPMIbiomass = { ...
            model_7_ctrl, ...
            model_7_sc1, ...
            model_7_sc12, ...
            model_7_sc2};

        save( ...
            fullfile(cfg.modelsDir, ...
            'models_7_RPMIbiomass.mat'), ...
            'models_7_RPMIbiomass');

    end

    %% 769-p sample-specific models

    if buildCellLineSampleModels

        fprintf('\nBuilding 769-p sample-specific models...\n');

        models_keep_7sample = zeros( ...
            numel(consistent_model.rxns), ...
            numel(colnames7));

        for i = 1:numel(colnames7)

            fprintf('769-p sample %d of %d\n', ...
                i, numel(colnames7));

            [ContextModel, A_keep] = fastcormics_RNAseq( ...
                consistent_model, ...
                discretized7(:, i), ...
                geneSyms7, ...
                dico, ...
                biomass_rxn, ...
                already_mapped_tag, ...
                consensus_proportion, ...
                epsilon, ...
                optional_settings);

            sampleName = matlab.lang.makeValidName( ...
                colnames7{i});

            outputFile = fullfile( ...
                cfg.modelsDir, ...
                ['Sample_769p_' sampleName '.mat']);

            save(outputFile, 'ContextModel');

            models_keep_7sample(A_keep, i) = 1;

        end

        save( ...
            fullfile(cfg.modelsDir, ...
            'models_keep_7sample.mat'), ...
            'models_keep_7sample', ...
            'colnames7');

    end

end

%% ============================================================
% TCGA MODELS
%% ============================================================

if strcmpi(cfg.runMode, 'TCGA') || ...
        strcmpi(cfg.runMode, 'ALL')

    fprintf('\n========================================\n');
    fprintf('TCGA MODELS\n');
    fprintf('========================================\n');

    % Kidney cancers use RPMI.
    % Liver cancer uses DMEM.

    tcgaList = { ...
        'KICH', 'ON',  'RPMI'; ...
        'KICH', 'OFF', 'RPMI'; ...
        'KIRC', 'ON',  'RPMI'; ...
        'KIRC', 'OFF', 'RPMI'; ...
        'KIRP', 'ON',  'RPMI'; ...
        'KIRP', 'OFF', 'RPMI'; ...
        'LIHC', 'ON',  'DMEM'; ...
        'LIHC', 'OFF', 'DMEM'};

    kidneyModels = {};
    kidneyModelNames = {};

    liverModels = {};
    liverModelNames = {};

    for k = 1:size(tcgaList, 1)

        cancer = tcgaList{k, 1};
        state = tcgaList{k, 2};
        mediumName = tcgaList{k, 3};

        fprintf('\n----------------------------------------\n');
        fprintf('Preparing TCGA model: %s_%s\n', ...
            cancer, state);
        fprintf('Medium: %s\n', mediumName);

        %% Determine prepared file and variables

        if strcmpi(state, 'ON')

            preparedName = ...
                ['discretizedON_' cancer '.mat'];

            preparedFile = find_prepared_file( ...
                cfg, preparedName);

            D = load(preparedFile);

            requiredVariables = { ...
                'discretizedon', ...
                'geneSymson', ...
                'colnamesON'};

            check_required_variables( ...
                D, requiredVariables, preparedFile);

            discretized_current = D.discretizedon;
            rownames = D.geneSymson;
            colnames_current = D.colnamesON;

        else

            preparedName = ...
                ['discretizedOFF_' cancer '.mat'];

            preparedFile = find_prepared_file( ...
                cfg, preparedName);

            D = load(preparedFile);

            requiredVariables = { ...
                'discretizedoff', ...
                'geneSymsoff', ...
                'colnamesOFF'};

            check_required_variables( ...
                D, requiredVariables, preparedFile);

            discretized_current = D.discretizedoff;
            rownames = D.geneSymsoff;
            colnames_current = D.colnamesOFF;

        end

        fprintf('Prepared file:\n%s\n', preparedFile);
        fprintf('Genes: %d\n', size(discretized_current, 1));
        fprintf('Samples: %d\n', size(discretized_current, 2));

        %% Assign medium by cancer type

        if strcmpi(mediumName, 'RPMI')
            optional_settings.medium = medium_RPMI_7;
        else
            optional_settings.medium = medium_DMEM_H;
        end

        %% ----------------------------------------------------
        % TCGA consensus model
        %% ----------------------------------------------------

        if buildConsensusModels

            fprintf('Building consensus model %s_%s...\n', ...
                cancer, state);

            [ContextModel, A_keep] = fastcormics_RNAseq( ...
                consistent_model, ...
                discretized_current, ...
                rownames, ...
                dico, ...
                biomass_rxn, ...
                already_mapped_tag, ...
                consensus_proportion, ...
                epsilon, ...
                optional_settings);

            modelName = ['model_' cancer '_' state];

            models_keep = zeros( ...
                numel(consistent_model.rxns), 1);

            models_keep(A_keep) = 1;

            outputFile = fullfile( ...
                cfg.modelsDir, ...
                [modelName '.mat']);

            save( ...
                outputFile, ...
                'ContextModel', ...
                'models_keep', ...
                'colnames_current', ...
                'rownames');

            fprintf('Saved consensus model:\n%s\n', outputFile);

            if strcmpi(cancer, 'LIHC')

                liverModels{end + 1} = ContextModel;
                liverModelNames{end + 1} = modelName;

            else

                kidneyModels{end + 1} = ContextModel;
                kidneyModelNames{end + 1} = modelName;

            end

        end

        %% ----------------------------------------------------
        % TCGA sample-specific models
        %% ----------------------------------------------------

        if buildTCGASampleModels

            fprintf('Building sample-specific models for %s_%s...\n', ...
                cancer, state);

            models_keep_samples = zeros( ...
                numel(consistent_model.rxns), ...
                numel(colnames_current));

            for i = 1:numel(colnames_current)

                fprintf('%s_%s sample %d of %d\n', ...
                    cancer, ...
                    state, ...
                    i, ...
                    numel(colnames_current));

                [SampleContextModel, A_keep_sample] = ...
                    fastcormics_RNAseq( ...
                    consistent_model, ...
                    discretized_current(:, i), ...
                    rownames, ...
                    dico, ...
                    biomass_rxn, ...
                    already_mapped_tag, ...
                    consensus_proportion, ...
                    epsilon, ...
                    optional_settings);

                sampleName = matlab.lang.makeValidName( ...
                    colnames_current{i});

                sampleOutput = fullfile( ...
                    cfg.modelsDir, ...
                    ['Sample_' cancer '_' state '_' ...
                    sampleName '.mat']);

                ContextModel = SampleContextModel;

                save(sampleOutput, 'ContextModel');

                models_keep_samples(A_keep_sample, i) = 1;

            end

            keepOutput = fullfile( ...
                cfg.modelsDir, ...
                ['models_keep_' cancer '_' state '.mat']);

            save( ...
                keepOutput, ...
                'models_keep_samples', ...
                'colnames_current', ...
                'rownames');

        end

    end

    %% Save grouped consensus models

    if buildConsensusModels

        models_Kidney_RPMIbiomass = kidneyModels;
        modelNames_kidney = kidneyModelNames;

        models_Liver_DMEMbiomass = liverModels;
        modelNames_liver = liverModelNames;

        save( ...
            fullfile(cfg.modelsDir, ...
            'models_Kidney_RPMIbiomass.mat'), ...
            'models_Kidney_RPMIbiomass', ...
            'modelNames_kidney');

        save( ...
            fullfile(cfg.modelsDir, ...
            'models_Liver_DMEMbiomass.mat'), ...
            'models_Liver_DMEMbiomass', ...
            'modelNames_liver');

        save( ...
            fullfile(cfg.modelsDir, ...
            'driverModel_WithoutO2onoff_TCGA.mat'), ...
            'consistent_model', ...
            'models_Kidney_RPMIbiomass', ...
            'models_Liver_DMEMbiomass', ...
            'modelNames_kidney', ...
            'modelNames_liver');

    end

end

fprintf('\ndriverModel_clean finished successfully.\n');

%% ============================================================
% LOCAL FUNCTIONS
%% ============================================================

function preparedFile = find_prepared_file(cfg, fileName)
% Search first in cfg.preparedDir and then in cfg.rootDir.

preparedFile = fullfile(cfg.preparedDir, fileName);

if exist(preparedFile, 'file') == 2
    return;
end

preparedFile = fullfile(cfg.rootDir, fileName);

if exist(preparedFile, 'file') == 2
    return;
end

error(['Cannot find prepared file:\n%s\n\n' ...
       'Checked:\n%s\n%s'], ...
       fileName, ...
       fullfile(cfg.preparedDir, fileName), ...
       fullfile(cfg.rootDir, fileName));

end

function check_required_variables(S, requiredVariables, sourceFile)
% Confirm that a loaded MAT file contains required variables.

for i = 1:numel(requiredVariables)

    variableName = requiredVariables{i};

    if ~isfield(S, variableName)
        error( ...
            'File %s is missing variable "%s".', ...
            sourceFile, ...
            variableName);
    end

end

end