clear;
clc;
close all;

%% =========================================================
% INPUT FILES
% =========================================================

file_LIHC = 'LIHC_SFVA41.xlsx';
file_Huh7 = 'Hsc12.xlsx';

file_KIRC = 'KIRC_SFVA41.xlsx';
file_769P = '7sc12.xlsx';

numPathways = 41;

%% =========================================================
% READ AND SORT EACH DATASET INDEPENDENTLY
% =========================================================

[pLIHC, sLIHC] = read_FVA_xlsx(file_LIHC);
[pHuh7, sHuh7] = read_FVA_xlsx(file_Huh7);

[pKIRC, sKIRC] = read_FVA_xlsx(file_KIRC);
[p769P, s769P] = read_FVA_xlsx(file_769P);

[pLIHC, sLIHC] = prepare_FVA(pLIHC, sLIHC, numPathways);
[pHuh7, sHuh7] = prepare_FVA(pHuh7, sHuh7, numPathways);

[pKIRC, sKIRC] = prepare_FVA(pKIRC, sKIRC, numPathways);
[p769P, s769P] = prepare_FVA(p769P, s769P, numPathways);

%% =========================================================
% FIGURE
% =========================================================

fig = figure( ...
    'Position', [50, 50, 1500, 900], ...
    'Color', 'w');

%% White-to-red colormap
% 0.1 = white
% 0.4 = red
nColors = 256;

whiteRed = [ ...
    ones(nColors,1), ...
    linspace(1,0,nColors)', ...
    linspace(1,0,nColors)' ...
];

%% =========================================================
% PANEL h: LIHC AND Huh7
% =========================================================

% LIHC axis
ax1 = axes( ...
    'Parent', fig, ...
    'Position', [0.225, 0.16, 0.040, 0.72]);

imagesc(ax1, sLIHC(:));
colormap(ax1, whiteRed);
caxis(ax1, [0.1 0.4]);

set(ax1, ...
    'YTick', 1:numel(sLIHC), ...
    'YTickLabel', cellstr(pLIHC), ...
    'XTick', [], ...
    'YAxisLocation', 'left', ...
    'TickLabelInterpreter', 'none', ...
    'FontSize', 7, ...
    'Box', 'on', ...
    'LineWidth', 0.5);

title(ax1, 'LIHC', ...
    'FontSize', 11, ...
    'FontWeight', 'bold');

draw_cell_grid(ax1, numel(sLIHC));

% Huh7 axis
ax2 = axes( ...
    'Parent', fig, ...
    'Position', [0.275, 0.16, 0.040, 0.72]);

imagesc(ax2, sHuh7(:));
colormap(ax2, whiteRed);
caxis(ax2, [0.1 0.4]);

set(ax2, ...
    'YTick', 1:numel(sHuh7), ...
    'YTickLabel', cellstr(pHuh7), ...
    'XTick', [], ...
    'YAxisLocation', 'right', ...
    'TickLabelInterpreter', 'none', ...
    'FontSize', 7, ...
    'Box', 'on', ...
    'LineWidth', 0.5);

title(ax2, 'Huh7', ...
    'FontSize', 11, ...
    'FontWeight', 'bold');

draw_cell_grid(ax2, numel(sHuh7));

% Panel label
annotation(fig, 'textbox', ...
    [0.075, 0.91, 0.05, 0.05], ...
    'String', 'h.', ...
    'FontSize', 18, ...
    'FontWeight', 'bold', ...
    'EdgeColor', 'none');

% Group title
annotation(fig, 'textbox', ...
    [0.215, 0.91, 0.12, 0.04], ...
    'String', 'FVA similarity', ...
    'HorizontalAlignment', 'center', ...
    'FontSize', 10, ...
    'FontWeight', 'bold', ...
    'EdgeColor', 'none');

% Bottom comparison labels
annotation(fig, 'textbox', ...
    [0.200, 0.055, 0.09, 0.10], ...
    'String', {'AKR1A1^{low}', 'vs.', 'AKR1A1^{high}'}, ...
    'Interpreter', 'tex', ...
    'HorizontalAlignment', 'center', ...
    'FontSize', 9, ...
    'EdgeColor', 'none');

annotation(fig, 'textbox', ...
    [0.257, 0.055, 0.08, 0.10], ...
    'String', {'siAKR1A1', 'vs.', 'siSCR'}, ...
    'HorizontalAlignment', 'center', ...
    'FontSize', 9, ...
    'EdgeColor', 'none');

% Horizontal colorbar for panel h
cb1 = colorbar(ax2, 'southoutside');

set(cb1, ...
    'Position', [0.225, 0.035, 0.090, 0.020], ...
    'Limits', [0.1 0.4], ...
    'Ticks', [0.1 0.2 0.3 0.4], ...
    'XDir', 'reverse', ...
    'FontSize', 7);

xlabel(cb1, 'score');

%% =========================================================
% PANEL i: KIRC AND 769-P
% =========================================================

% KIRC axis
ax3 = axes( ...
    'Parent', fig, ...
    'Position', [0.665, 0.16, 0.040, 0.72]);

imagesc(ax3, sKIRC(:));
colormap(ax3, whiteRed);
caxis(ax3, [0.1 0.4]);

set(ax3, ...
    'YTick', 1:numel(sKIRC), ...
    'YTickLabel', cellstr(pKIRC), ...
    'XTick', [], ...
    'YAxisLocation', 'left', ...
    'TickLabelInterpreter', 'none', ...
    'FontSize', 7, ...
    'Box', 'on', ...
    'LineWidth', 0.5);

title(ax3, 'KIRC', ...
    'FontSize', 11, ...
    'FontWeight', 'bold');

draw_cell_grid(ax3, numel(sKIRC));

% 769-P axis
ax4 = axes( ...
    'Parent', fig, ...
    'Position', [0.715, 0.16, 0.040, 0.72]);

imagesc(ax4, s769P(:));
colormap(ax4, whiteRed);
caxis(ax4, [0.1 0.4]);

set(ax4, ...
    'YTick', 1:numel(s769P), ...
    'YTickLabel', cellstr(p769P), ...
    'XTick', [], ...
    'YAxisLocation', 'right', ...
    'TickLabelInterpreter', 'none', ...
    'FontSize', 7, ...
    'Box', 'on', ...
    'LineWidth', 0.5);

title(ax4, '769-P', ...
    'FontSize', 11, ...
    'FontWeight', 'bold');

draw_cell_grid(ax4, numel(s769P));

% Panel label
annotation(fig, 'textbox', ...
    [0.490, 0.91, 0.05, 0.05], ...
    'String', 'i.', ...
    'FontSize', 18, ...
    'FontWeight', 'bold', ...
    'EdgeColor', 'none');

% Group title
annotation(fig, 'textbox', ...
    [0.655, 0.91, 0.12, 0.04], ...
    'String', 'FVA similarity', ...
    'HorizontalAlignment', 'center', ...
    'FontSize', 10, ...
    'FontWeight', 'bold', ...
    'EdgeColor', 'none');

% Bottom comparison labels
annotation(fig, 'textbox', ...
    [0.640, 0.055, 0.09, 0.10], ...
    'String', {'AKR1A1^{low}', 'vs.', 'AKR1A1^{high}'}, ...
    'Interpreter', 'tex', ...
    'HorizontalAlignment', 'center', ...
    'FontSize', 9, ...
    'EdgeColor', 'none');

annotation(fig, 'textbox', ...
    [0.697, 0.055, 0.08, 0.10], ...
    'String', {'siAKR1A1', 'vs.', 'siSCR'}, ...
    'HorizontalAlignment', 'center', ...
    'FontSize', 9, ...
    'EdgeColor', 'none');

% Horizontal colorbar for panel i
cb2 = colorbar(ax4, 'southoutside');

set(cb2, ...
    'Position', [0.665, 0.035, 0.090, 0.020], ...
    'Limits', [0.1 0.4], ...
    'Ticks', [0.1 0.2 0.3 0.4], ...
    'XDir', 'reverse', ...
    'FontSize', 7);

xlabel(cb2, 'score');

%% =========================================================
% SAVE
% =========================================================

saveas(fig, 'Figure_S1_hi_FVA_similarity.svg');
saveas(fig, 'Figure_S1_hi_FVA_similarity.pdf');

fprintf('\nCreated:\n');
fprintf('Figure_S1_hi_FVA_similarity.svg\n');
fprintf('Figure_S1_hi_FVA_similarity.pdf\n');

%% =========================================================
% FUNCTIONS
% =========================================================

function [pathways, scores] = prepare_FVA(pathways, scores, nRequested)

    % Ascending order:
    % low/white pathways at top
    % high/red pathways at bottom
    [scores, idx] = sort(scores, 'ascend');
    pathways = pathways(idx);

    n = min(nRequested, numel(scores));

    pathways = pathways(1:n);
    scores = scores(1:n);
end

function draw_cell_grid(ax, nRows)

    hold(ax, 'on');

    for y = 0.5:1:(nRows + 0.5)
        line(ax, [0.5 1.5], [y y], ...
            'Color', [0.45 0.45 0.45], ...
            'LineWidth', 0.25);
    end

    line(ax, [0.5 0.5], [0.5 nRows + 0.5], ...
        'Color', [0.35 0.35 0.35], ...
        'LineWidth', 0.4);

    line(ax, [1.5 1.5], [0.5 nRows + 0.5], ...
        'Color', [0.35 0.35 0.35], ...
        'LineWidth', 0.4);

    hold(ax, 'off');
end

function [pathways, scores] = read_FVA_xlsx(filename)

    if ~exist(filename, 'file')
        error('Input file not found: %s', filename);
    end

    [~, ~, raw] = xlsread(filename);

    if isempty(raw)
        error('File is empty or could not be read: %s', filename);
    end

    if size(raw,2) < 2
        error('File %s must contain at least two columns.', filename);
    end

    header = raw(1,:);
    pathwayCol = [];

    for j = 1:numel(header)

        headerName = strtrim(char(string(header{j})));

        if strcmpi(headerName, 'Pathways') || ...
           strcmpi(headerName, 'Pathway') || ...
           strcmpi(headerName, 'subSys') || ...
           strcmpi(headerName, 'Subsystem')

            pathwayCol = j;
            break;
        end
    end

    if isempty(pathwayCol)
        pathwayCol = 1;
    end

    scoreCol = 2;

    pathwayCells = raw(2:end, pathwayCol);
    scoreCells = raw(2:end, scoreCol);

    pathways = strings(numel(pathwayCells),1);
    scores = nan(numel(scoreCells),1);

    for r = 1:numel(pathwayCells)

        if isempty(pathwayCells{r})
            pathways(r) = "";
        else
            pathways(r) = string(pathwayCells{r});
        end

        value = scoreCells{r};

        if isnumeric(value) && isscalar(value)
            scores(r) = value;
        else
            scores(r) = str2double(string(value));
        end
    end

    valid = ...
        ~isnan(scores) & ...
        strlength(strtrim(pathways)) > 0;

    pathways = pathways(valid);
    scores = scores(valid);

    if isempty(scores)
        error('No valid FVA scores found in %s.', filename);
    end
end