%% driverModel_shared.m
%
% Shared FASTCORMICS driver for:
%
% CELL LINES
%   Huh7  -> DMEM
%   769-P -> RPMI
%
% TCGA AKR1A1 ON/OFF
%   KICH -> RPMI
%   KIRC -> RPMI
%   KIRP -> RPMI
%   LIHC -> DMEM
%
% MATLAB R2019b compatible.
%
% Original FASTCORMICS settings, model names and sample groupings
% are preserved.

clear;
close all;
clc;

feature astheightlimit 2000
solverOK = 1;

%% ============================================================
% EXECUTION MODE
%% ============================================================

% Options:
%   'CELL_LINES'
%   'TCGA'
%   'ALL'

runMode = 'ALL';

%% ============================================================
% RELATIVE PATHS
%% ============================================================

preparedDir = fullfile('data','prepared');
referenceDir = fullfile('data','model');
mediumDir = fullfile('data','medium');
outputDir = fullfile('results','models');

if exist(outputDir,'dir') ~= 7
    mkdir(outputDir);
end

%% ============================================================
% LOAD MODEL AND DICTIONARY
%% ============================================================

consistentModelFile = fullfile(referenceDir,'consistent_model.mat');
dictionaryFile = fullfile(referenceDir,'dico2columns.mat');

if exist(consistentModelFile,'file') ~= 2
    error('File not found: %s',consistentModelFile);
end

if exist(dictionaryFile,'file') ~= 2
    error('File not found: %s',dictionaryFile);
end

load(consistentModelFile);
load(dictionaryFile);

%% Close superoxide exchange

consistent_model.lb( ...
    ismember(consistent_model.rxns,'EX_o2s[e]')) = 0;

%% FASTCORMICS settings

already_mapped_tag = 0;
consensus_proportion = 0.9;
epsilon = 1e-4;
biomass_rxn = 'biomass_reaction';

unpenalizedSystems = {
    'Transport, endoplasmic reticular'
    'Transport, extracellular'
    'Transport, golgi apparatus'
    'Transport, mitochondrial'
    'Transport, peroxisomal'
    'Transport, lysosomal'
    'Transport, nuclear'
};

unpenalized = consistent_model.rxns( ...
    ismember(consistent_model.subSystems,unpenalizedSystems));

%% ============================================================
% LOAD MEDIA
%% ============================================================

mediumDMEMFile = fullfile(mediumDir,'medium_DMEM_H.xlsx');
mediumRPMIFile = fullfile(mediumDir,'medium_RPMI_7.xlsx');

if exist(mediumDMEMFile,'file') ~= 2
    error('File not found: %s',mediumDMEMFile);
end

if exist(mediumRPMIFile,'file') ~= 2
    error('File not found: %s',mediumRPMIFile);
end

medium_DMEM_H = readtable( ...
    mediumDMEMFile, ...
    'ReadVariableNames',false);

medium_DMEM_H = table2array(medium_DMEM_H);

medium_RPMI_7 = readtable( ...
    mediumRPMIFile, ...
    'ReadVariableNames',false);

medium_RPMI_7 = table2array(medium_RPMI_7);

save(fullfile(outputDir,'medium_DMEM_H.mat'),'medium_DMEM_H');
save(fullfile(outputDir,'medium_RPMI_7.mat'),'medium_RPMI_7');

%% ============================================================
% CELL-LINE MODELS
%% ============================================================

if strcmpi(runMode,'CELL_LINES') || strcmpi(runMode,'ALL')

    %% ========================================================
    % Huh7 — DMEM
    %% ========================================================

    discretizedHFile = fullfile(preparedDir,'discretizedH.mat');

    if exist(discretizedHFile,'file') ~= 2
        error('File not found: %s',discretizedHFile);
    end

    load(discretizedHFile, ...
        'discretized', ...
        'geneSyms', ...
        'colnamesH');

    rownames = geneSyms;

    optional_settings.unpenalized = unpenalized;
    optional_settings.medium = medium_DMEM_H;
    optional_settings.not_medium_constrained = [];
    optional_settings.func = {
        'DM_atp_c_'
        'biomass_reaction'
    };

    %% Huh7 consensus models

    [model_H_ctrl,~] = fastcormics_RNAseq( ...
        consistent_model, ...
        discretized(:,[1,2,3,11]), ...
        rownames, ...
        dico, ...
        biomass_rxn, ...
        already_mapped_tag, ...
        consensus_proportion, ...
        epsilon, ...
        optional_settings);

    [model_H_sc1,~] = fastcormics_RNAseq( ...
        consistent_model, ...
        discretized(:,4:6), ...
        rownames, ...
        dico, ...
        biomass_rxn, ...
        already_mapped_tag, ...
        consensus_proportion, ...
        epsilon, ...
        optional_settings);

    [model_H_sc2,~] = fastcormics_RNAseq( ...
        consistent_model, ...
        discretized(:,7:10), ...
        rownames, ...
        dico, ...
        biomass_rxn, ...
        already_mapped_tag, ...
        consensus_proportion, ...
        epsilon, ...
        optional_settings);

    [model_H_sc12,~] = fastcormics_RNAseq( ...
        consistent_model, ...
        discretized(:,4:10), ...
        rownames, ...
        dico, ...
        biomass_rxn, ...
        already_mapped_tag, ...
        consensus_proportion, ...
        epsilon, ...
        optional_settings);

    %% Huh7 sample-specific models

    models_keep_Hsample = zeros( ...
        numel(consistent_model.rxns), ...
        numel(colnamesH));

    for i = 1:numel(colnamesH)

        disp('H: ');
        disp(i);

        [ContextModel,A_keep] = fastcormics_RNAseq( ...
            consistent_model, ...
            discretized(:,i), ...
            rownames, ...
            dico, ...
            biomass_rxn, ...
            already_mapped_tag, ...
            consensus_proportion, ...
            epsilon, ...
            optional_settings);

        name = fullfile( ...
            outputDir, ...
            ['Sample' colnamesH{i} '.mat']);

        save(name,'ContextModel');

        models_keep_Hsample(A_keep,i) = 1;
    end

    %% ========================================================
    % 769-P — RPMI
    %% ========================================================

    discretized7File = fullfile(preparedDir,'discretized7.mat');

    if exist(discretized7File,'file') ~= 2
        error('File not found: %s',discretized7File);
    end

    load(discretized7File, ...
        'discretized', ...
        'geneSyms', ...
        'colnames7');

    rownames = geneSyms;

    optional_settings.unpenalized = unpenalized;
    optional_settings.medium = medium_RPMI_7;
    optional_settings.not_medium_constrained = [];
    optional_settings.func = {
        'DM_atp_c_'
        'biomass_reaction'
    };

    %% 769-P consensus models

    [model_7_ctrl,~] = fastcormics_RNAseq( ...
        consistent_model, ...
        discretized(:,[1,2,3,4]), ...
        rownames, ...
        dico, ...
        biomass_rxn, ...
        already_mapped_tag, ...
        consensus_proportion, ...
        epsilon, ...
        optional_settings);

    [model_7_sc1,~] = fastcormics_RNAseq( ...
        consistent_model, ...
        discretized(:,[5,6,7]), ...
        rownames, ...
        dico, ...
        biomass_rxn, ...
        already_mapped_tag, ...
        consensus_proportion, ...
        epsilon, ...
        optional_settings);

    [model_7_sc2,~] = fastcormics_RNAseq( ...
        consistent_model, ...
        discretized(:,[8,9,10,11]), ...
        rownames, ...
        dico, ...
        biomass_rxn, ...
        already_mapped_tag, ...
        consensus_proportion, ...
        epsilon, ...
        optional_settings);

    [model_7_sc12,~] = fastcormics_RNAseq( ...
        consistent_model, ...
        discretized(:,5:11), ...
        rownames, ...
        dico, ...
        biomass_rxn, ...
        already_mapped_tag, ...
        consensus_proportion, ...
        epsilon, ...
        optional_settings);

    %% 769-P sample-specific models

    models_keep_7sample = zeros( ...
        numel(consistent_model.rxns), ...
        numel(colnames7));

    for i = 1:numel(colnames7)

        disp('7: ');
        disp(i);

        [ContextModel,A_keep] = fastcormics_RNAseq( ...
            consistent_model, ...
            discretized(:,i), ...
            rownames, ...
            dico, ...
            biomass_rxn, ...
            already_mapped_tag, ...
            consensus_proportion, ...
            epsilon, ...
            optional_settings);

        name = fullfile( ...
            outputDir, ...
            ['Sample' colnames7{i} '.mat']);

        save(name,'ContextModel');

        models_keep_7sample(A_keep,i) = 1;
    end

    %% Save original cell-line output filename

    save( ...
        fullfile(outputDir,'driverModel_WithoutO2.mat'), ...
        'consistent_model', ...
        'colnamesH', ...
        'colnames7', ...
        'models_keep_Hsample', ...
        'models_keep_7sample', ...
        'model_H_ctrl', ...
        'model_H_sc1', ...
        'model_H_sc2', ...
        'model_H_sc12', ...
        'model_7_ctrl', ...
        'model_7_sc1', ...
        'model_7_sc2', ...
        'model_7_sc12');

end

%% ============================================================
% TCGA ON/OFF MODELS
%% ============================================================

if strcmpi(runMode,'TCGA') || strcmpi(runMode,'ALL')

    cancers = {
        'KICH'
        'KIRC'
        'KIRP'
        'LIHC'
    };

    for cancerIndex = 1:numel(cancers)

        cancer = cancers{cancerIndex};

        fprintf('\nBuilding %s ON/OFF models\n',cancer);

        %% Correct medium by tissue

        if strcmp(cancer,'KICH') || ...
           strcmp(cancer,'KIRC') || ...
           strcmp(cancer,'KIRP')

            reconstructionMedium = medium_RPMI_7;
            mediumName = 'RPMI';

        elseif strcmp(cancer,'LIHC')

            reconstructionMedium = medium_DMEM_H;
            mediumName = 'DMEM';

        else
            error('Medium not defined for %s.',cancer);
        end

        fprintf('%s uses %s\n',cancer,mediumName);

        optional_settings.unpenalized = unpenalized;
        optional_settings.medium = reconstructionMedium;
        optional_settings.not_medium_constrained = [];
        optional_settings.func = {
            'DM_atp_c_'
            'biomass_reaction'
        };

        %% ====================================================
        % ON
        %% ====================================================

        onFile = fullfile( ...
            preparedDir, ...
            ['discretizedON_' cancer '.mat']);

        if exist(onFile,'file') ~= 2
            error('File not found: %s',onFile);
        end

        load(onFile, ...
            'discretizedon', ...
            'geneSymson', ...
            'colnamesON');

        rownames = geneSymson;

        %% ON consensus model

        [modelON,~] = fastcormics_RNAseq( ...
            consistent_model, ...
            discretizedon, ...
            rownames, ...
            dico, ...
            biomass_rxn, ...
            already_mapped_tag, ...
            consensus_proportion, ...
            epsilon, ...
            optional_settings);

        %% ON sample-specific models

        modelsKeepON = zeros( ...
            numel(consistent_model.rxns), ...
            numel(colnamesON));

        for i = 1:numel(colnamesON)

            fprintf('%s ON sample %d\n',cancer,i);

            [ContextModel,A_keep] = fastcormics_RNAseq( ...
                consistent_model, ...
                discretizedon(:,i), ...
                rownames, ...
                dico, ...
                biomass_rxn, ...
                already_mapped_tag, ...
                consensus_proportion, ...
                epsilon, ...
                optional_settings);

            name = fullfile( ...
                outputDir, ...
                ['Sample' cancer '_ON_' colnamesON{i} '.mat']);

            save(name,'ContextModel');

            modelsKeepON(A_keep,i) = 1;
        end

        %% ====================================================
        % OFF
        %% ====================================================

        offFile = fullfile( ...
            preparedDir, ...
            ['discretizedOFF_' cancer '.mat']);

        if exist(offFile,'file') ~= 2
            error('File not found: %s',offFile);
        end

        load(offFile, ...
            'discretizedoff', ...
            'geneSymsoff', ...
            'colnamesOFF');

        rownames = geneSymsoff;

        %% OFF consensus model

        [modelOFF,~] = fastcormics_RNAseq( ...
            consistent_model, ...
            discretizedoff, ...
            rownames, ...
            dico, ...
            biomass_rxn, ...
            already_mapped_tag, ...
            consensus_proportion, ...
            epsilon, ...
            optional_settings);

        %% OFF sample-specific models

        modelsKeepOFF = zeros( ...
            numel(consistent_model.rxns), ...
            numel(colnamesOFF));

        for i = 1:numel(colnamesOFF)

            fprintf('%s OFF sample %d\n',cancer,i);

            [ContextModel,A_keep] = fastcormics_RNAseq( ...
                consistent_model, ...
                discretizedoff(:,i), ...
                rownames, ...
                dico, ...
                biomass_rxn, ...
                already_mapped_tag, ...
                consensus_proportion, ...
                epsilon, ...
                optional_settings);

            name = fullfile( ...
                outputDir, ...
                ['Sample' cancer '_OFF_' colnamesOFF{i} '.mat']);

            save(name,'ContextModel');

            modelsKeepOFF(A_keep,i) = 1;
        end

        %% ====================================================
        % PRESERVE ORIGINAL VARIABLE AND FILE NAMES
        %% ====================================================

        switch cancer

            case 'KICH'

                model_KICH_ON = modelON;
                model_KICH_OFF = modelOFF;

                models_keep_onsample_KICH = modelsKeepON;
                models_keep_offsample_KICH = modelsKeepOFF;

                save( ...
                    fullfile(outputDir, ...
                    'driverModel_WithoutO2onoffKICH.mat'), ...
                    'model_KICH_ON', ...
                    'model_KICH_OFF', ...
                    'models_keep_onsample_KICH', ...
                    'models_keep_offsample_KICH', ...
                    'colnamesON', ...
                    'colnamesOFF', ...
                    'consistent_model');

            case 'KIRC'

                model_KIRC_ON = modelON;
                model_KIRC_OFF = modelOFF;

                models_keep_onsample_KIRC = modelsKeepON;
                models_keep_offsample_KIRC = modelsKeepOFF;

                save( ...
                    fullfile(outputDir, ...
                    'driverModel_WithoutO2onoffKIRC.mat'), ...
                    'model_KIRC_ON', ...
                    'model_KIRC_OFF', ...
                    'models_keep_onsample_KIRC', ...
                    'models_keep_offsample_KIRC', ...
                    'colnamesON', ...
                    'colnamesOFF', ...
                    'consistent_model');

            case 'KIRP'

                model_KIRP_ON = modelON;
                model_KIRP_OFF = modelOFF;

                models_keep_onsample_KIRP = modelsKeepON;
                models_keep_offsample_KIRP = modelsKeepOFF;

                save( ...
                    fullfile(outputDir, ...
                    'driverModel_WithoutO2onoffKIRP.mat'), ...
                    'model_KIRP_ON', ...
                    'model_KIRP_OFF', ...
                    'models_keep_onsample_KIRP', ...
                    'models_keep_offsample_KIRP', ...
                    'colnamesON', ...
                    'colnamesOFF', ...
                    'consistent_model');

            case 'LIHC'

                model_LIHC_ON = modelON;
                model_LIHC_OFF = modelOFF;

                models_keep_onsample_LIHC = modelsKeepON;
                models_keep_offsample_LIHC = modelsKeepOFF;

                save( ...
                    fullfile(outputDir, ...
                    'driverModel_WithoutO2onoffLIHC.mat'), ...
                    'model_LIHC_ON', ...
                    'model_LIHC_OFF', ...
                    'models_keep_onsample_LIHC', ...
                    'models_keep_offsample_LIHC', ...
                    'colnamesON', ...
                    'colnamesOFF', ...
                    'consistent_model');

        end

    end

    %% Save combined TCGA output using the original name

    save( ...
        fullfile(outputDir,'driverModel_WithoutO2offALL.mat'), ...
        'model_KICH_ON', ...
        'model_KICH_OFF', ...
        'model_KIRC_ON', ...
        'model_KIRC_OFF', ...
        'model_KIRP_ON', ...
        'model_KIRP_OFF', ...
        'model_LIHC_ON', ...
        'model_LIHC_OFF', ...
        'models_keep_onsample_KICH', ...
        'models_keep_offsample_KICH', ...
        'models_keep_onsample_KIRC', ...
        'models_keep_offsample_KIRC', ...
        'models_keep_onsample_KIRP', ...
        'models_keep_offsample_KIRP', ...
        'models_keep_onsample_LIHC', ...
        'models_keep_offsample_LIHC', ...
        'consistent_model');

end

disp('driverModel_shared finished');